[2022-04-07 00:47:10,834] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [None]>
[2022-04-07 00:47:10,842] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [None]>
[2022-04-07 00:47:10,842] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:47:10,842] {taskinstance.py:1095} INFO - Starting attempt 2 of 3
[2022-04-07 00:47:10,842] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:47:10,852] {taskinstance.py:1114} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_to_external_table_Task> on 2022-02-01T00:00:00+00:00
[2022-04-07 00:47:10,856] {standard_task_runner.py:52} INFO - Started process 454 to run task
[2022-04-07 00:47:10,858] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'gcs_to_external_table_Task', '2022-02-01T00:00:00+00:00', '--job-id', '247', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp4qx1g31_', '--error-file', '/tmp/tmp7n2a3p4g']
[2022-04-07 00:47:10,860] {standard_task_runner.py:77} INFO - Job 247: Subtask gcs_to_external_table_Task
[2022-04-07 00:47:10,890] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-07 00:47:10,931] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=gcs_to_external_table_Task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-07 00:47:10,932] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 00:47:10,941] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/hooks/bigquery.py:637 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.create_empty_table` method withpass passing the `table_resource` object. This gives more flexibility than this method.
[2022-04-07 00:47:10,942] {bigquery.py:700} INFO - Creating external table: sturdy-dogfish-344515.divvybikes_data_all.external_table         table_resource={
            "tableReference": {
                "projectId" : PROJECT_ID,
                "datasetId" : BIGQUERY_DATASET,
                "tableId"   : "external_table"
            } ,
            "externalDataConfiguration":{
                "sourceFormat" : "PARQUET",
                 "sourceUris": [f"gs://{BUCKET}/raw/*"],
            }
        }, 
[2022-04-07 00:47:11,444] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1215, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 702, in create_external_table
    table_resource=table.to_api_repr(), project_id=project_id, location=location, exists_ok=True
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 729, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 747, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/sturdy-dogfish-344515/datasets/divvybikes_data_all/tables?prettyPrint=false: Invalid table ID "external_table         table_resource={
            "tableReference": {
                "projectId" : PROJECT_ID,
                "datasetId" : BIGQUERY_DATASET,
                "tableId"   : "external_table"
            } ,
            "externalDataConfiguration":{
                "sourceFormat" : "PARQUET",
                 "sourceUris": [f"gs://{BUCKET}/raw/*"],
            }
        }, ".
[2022-04-07 00:47:11,447] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=gcs_to_external_table_Task, execution_date=20220201T000000, start_date=20220407T004710, end_date=20220407T004711
[2022-04-07 00:47:11,474] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-07 00:47:11,495] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 00:47:11,509] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [up_for_retry]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-07 00:47:11,511] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [success]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-07 00:47:11,512] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [success]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
