[2022-04-01 16:43:02,912] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [None]>
[2022-04-01 16:43:02,924] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [None]>
[2022-04-01 16:43:02,925] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 16:43:02,925] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-04-01 16:43:02,925] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 16:43:02,931] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): download_dataset> on 2022-03-01T00:00:00+00:00
[2022-04-01 16:43:02,935] {standard_task_runner.py:52} INFO - Started process 8099 to run task
[2022-04-01 16:43:02,938] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'download_dataset', '2022-03-01T00:00:00+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp5mea_rxj', '--error-file', '/tmp/tmppxcbvt2e']
[2022-04-01 16:43:02,940] {standard_task_runner.py:77} INFO - Job 61: Subtask download_dataset
[2022-04-01 16:43:02,975] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 16:43:03,019] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2022-04-01 16:43:03,448] {python.py:151} INFO - Done. Returned value was: None
[2022-04-01 16:43:03,458] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=divvybikes_elt_pipeline, task_id=download_dataset, execution_date=20220301T000000, start_date=20220401T164302, end_date=20220401T164303
[2022-04-01 16:43:03,513] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-04-01 16:43:03,535] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
